version: "3"

services:
  grafana:
    image: grafana/grafana:latest

    container_name: grafana
    hostname: grafana
    
    ports:
      - 9040:3000 
            
    volumes:
      - grafana-data:/var/lib/grafana                                         # Dashboards etc.
      - grafana-datasources:/etc/grafana/provisioning/datasources             # Datasource Konfiguration

    environment:
      - TZ=$TIMEZONE                                                          # Zeitzone via .env-FIle
      - GF_SECURITY_ADMIN_USER=$GRAFANA_USER                                  # Benutzername
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASSWORD                          # Passwort
      - GF_USERS_ALLOW_SIGN_UP=false                                          # Registrierung deaktivieren
      
    restart: always

    networks:
      - proxy

    labels:
      # Traefik
      - "traefik.http.routers.grafana.rule=Host(`monitor.$TLD`)"              # HTTP Domain 채ndern
      - "traefik.http.routers.grafana-secure.rule=Host(`monitor.$TLD`)"       # HTTP Domain 채ndern
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=http"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

      # Watchtower - Container automatisch 체berwachen, melden wenn neue Version verf체gbar ist
      - "com.centurylinklabs.watchtower.monitor-only=true"

networks:
  proxy:
    external: true

volumes:
  grafana-data:
    name: grafana-data

  grafana-datasources:
    name: grafana-datasources